/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.administrator;

import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.college.College;
import info5100.university.example.university.University;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chara
 */
public class AdminPortal extends javax.swing.JPanel {

    /**
     * Creates new form AdminPortal
     */
    Department department;
    University university;
    College college;
    FacultyProfile facultyprofile ;
    FacultyDirectory facultydirectory;
    StudentProfile studentProfile;
    StudentDirectory studentDirectory;
   
    
    public AdminPortal(University university, FacultyDirectory fd, StudentDirectory sd) {
        this.university = university;
        this.studentDirectory = sd;
        this.facultydirectory = fd;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane_Admin = new javax.swing.JTabbedPane();
        jPanel_Analytics = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGenerateReports = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        courseData = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        financialData = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel_Course_Management = new javax.swing.JPanel();
        btnAddToCatalog = new javax.swing.JButton();
        btnViewCatalog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listCourseMgmtClg = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCmCatalog = new javax.swing.JList<>();
        btnSearchCourses = new javax.swing.JButton();
        listCorseMgmtDpmtList = new javax.swing.JComboBox<>();
        jPanelCourse = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCMcourseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCMCourseNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCMcr = new javax.swing.JTextField();
        jPanel_Schedule_Management = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scheduleMgtDpmtList = new javax.swing.JComboBox<>();
        scheduleMgmtClgList = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scheduleSemList = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtNoOfSeats = new javax.swing.JTextField();
        btnAddSchedule = new javax.swing.JButton();
        schdlMgmtGetSchedule = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        facultyList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        courseListSchdMgmt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel_University_Management = new javax.swing.JPanel();
        jPanelCollege_Directory = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        getClgDir = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtAddCollege = new javax.swing.JTextField();
        btnAddcolleges = new javax.swing.JButton();
        btnGetClgDirectory = new javax.swing.JButton();
        jPanelDep_Dir = new javax.swing.JPanel();
        getDepartment = new javax.swing.JButton();
        clgDirDptMgmt = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        addDeptList = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtAddDept = new javax.swing.JTextField();
        btnAddDepartment = new javax.swing.JButton();
        jPanelSem_Updt = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        listClgSemUpdate = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        listDpmtSemUdt = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        listSemUpt = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtSemUpdt = new javax.swing.JTextField();
        btnAddSem = new javax.swing.JButton();
        btnSemUpdt = new javax.swing.JButton();
        jPanel_Directories = new javax.swing.JPanel();
        jPanelAdd_Std = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        btnStudentAdd = new javax.swing.JButton();
        jPanelStd_Dir = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentDirList = new javax.swing.JTable();
        btnGetStudentDirectory = new javax.swing.JButton();
        jPanelFac_Dir = new javax.swing.JPanel();
        btnGetDirectoryList = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        facultyDirectoryList = new javax.swing.JTable();
        jPanelAdd_Fac = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtAddFaculty = new javax.swing.JTextField();
        btnAddFaculty = new javax.swing.JButton();

        btnGenerateReports.setText("Generate Reports");
        btnGenerateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportsActionPerformed(evt);
            }
        });

        courseData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Courses", "Faculty", "Total Seats"
            }
        ));
        jScrollPane5.setViewportView(courseData);

        financialData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "College", "Department", "Total Revenue", "Revenue Lost"
            }
        ));
        jScrollPane6.setViewportView(financialData);

        jLabel35.setText("Course data");

        jLabel36.setText("Financial Stats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnGenerateReports)))
                .addGap(231, 453, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnGenerateReports)
                .addGap(38, 38, 38)
                .addComponent(jLabel35)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_AnalyticsLayout = new javax.swing.GroupLayout(jPanel_Analytics);
        jPanel_Analytics.setLayout(jPanel_AnalyticsLayout);
        jPanel_AnalyticsLayout.setHorizontalGroup(
            jPanel_AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_AnalyticsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_AnalyticsLayout.setVerticalGroup(
            jPanel_AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_AnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_AnalyticsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane_Admin.addTab("Analytics", jPanel_Analytics);

        btnAddToCatalog.setText("Add to catalog");
        btnAddToCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCatalogActionPerformed(evt);
            }
        });

        btnViewCatalog.setText("View catalog");
        btnViewCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCatalogActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("College:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Department:");

        listCourseMgmtClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCourseMgmtClgActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listCmCatalog);

        btnSearchCourses.setText("Search courses");
        btnSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCoursesActionPerformed(evt);
            }
        });

        listCorseMgmtDpmtList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCorseMgmtDpmtListActionPerformed(evt);
            }
        });

        jPanelCourse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Course Name:");

        txtCMcourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMcourseNameActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Course Number:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Course Credits:");

        javax.swing.GroupLayout jPanelCourseLayout = new javax.swing.GroupLayout(jPanelCourse);
        jPanelCourse.setLayout(jPanelCourseLayout);
        jPanelCourseLayout.setHorizontalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCourseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCMcr)
                        .addComponent(txtCMCourseNo)
                        .addComponent(txtCMcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelCourseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        jPanelCourseLayout.setVerticalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCourseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCMcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCMCourseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCMcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_Course_ManagementLayout = new javax.swing.GroupLayout(jPanel_Course_Management);
        jPanel_Course_Management.setLayout(jPanel_Course_ManagementLayout);
        jPanel_Course_ManagementLayout.setHorizontalGroup(
            jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddToCatalog)
                    .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearchCourses)
                        .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(listCorseMgmtDpmtList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(listCourseMgmtClg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnViewCatalog))
                    .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel_Course_ManagementLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6});

        jPanel_Course_ManagementLayout.setVerticalGroup(
            jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnSearchCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCatalog)
                        .addContainerGap(247, Short.MAX_VALUE))
                    .addGroup(jPanel_Course_ManagementLayout.createSequentialGroup()
                        .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(listCourseMgmtClg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Course_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(listCorseMgmtDpmtList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jPanelCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddToCatalog)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane_Admin.addTab("Course management", jPanel_Course_Management);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("College:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Department:");

        scheduleMgtDpmtList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleMgtDpmtListActionPerformed(evt);
            }
        });

        scheduleMgmtClgList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleMgmtClgListActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Course:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Semester:");

        scheduleSemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleSemListActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("No of seats:");

        btnAddSchedule.setText("Add to schedule");
        btnAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddScheduleActionPerformed(evt);
            }
        });

        schdlMgmtGetSchedule.setText("Get Data");
        schdlMgmtGetSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schdlMgmtGetScheduleActionPerformed(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Faculty:");

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Faculty", "Seats"
            }
        ));
        jScrollPane1.setViewportView(tblSchedule);

        courseListSchdMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseListSchdMgmtActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Scehdule:");

        javax.swing.GroupLayout jPanel_Schedule_ManagementLayout = new javax.swing.GroupLayout(jPanel_Schedule_Management);
        jPanel_Schedule_Management.setLayout(jPanel_Schedule_ManagementLayout);
        jPanel_Schedule_ManagementLayout.setHorizontalGroup(
            jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(scheduleSemList, 0, 95, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                        .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Schedule_ManagementLayout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(facultyList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Schedule_ManagementLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddSchedule)
                                        .addComponent(txtNoOfSeats))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(courseListSchdMgmt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(scheduleMgtDpmtList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(scheduleMgmtClgList, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(schdlMgmtGetSchedule)))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Schedule_ManagementLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel13, jLabel21, jLabel7, jLabel8});

        jPanel_Schedule_ManagementLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {courseListSchdMgmt, facultyList, scheduleMgmtClgList, scheduleMgtDpmtList, scheduleSemList});

        jPanel_Schedule_ManagementLayout.setVerticalGroup(
            jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Schedule_ManagementLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(scheduleMgmtClgList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schdlMgmtGetSchedule))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(scheduleMgtDpmtList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(scheduleSemList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(courseListSchdMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(facultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Schedule_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAddSchedule)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane_Admin.addTab("Schedule management", jPanel_Schedule_Management);

        jPanelCollege_Directory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "College Directory", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("College List:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("College:");

        txtAddCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCollegeActionPerformed(evt);
            }
        });

        btnAddcolleges.setText("Add College");
        btnAddcolleges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddcollegesActionPerformed(evt);
            }
        });

        btnGetClgDirectory.setText("Get Colleges");
        btnGetClgDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetClgDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCollege_DirectoryLayout = new javax.swing.GroupLayout(jPanelCollege_Directory);
        jPanelCollege_Directory.setLayout(jPanelCollege_DirectoryLayout);
        jPanelCollege_DirectoryLayout.setHorizontalGroup(
            jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollege_DirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCollege_DirectoryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddcolleges)
                        .addGap(32, 32, 32))
                    .addGroup(jPanelCollege_DirectoryLayout.createSequentialGroup()
                        .addGroup(jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getClgDir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddCollege))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCollege_DirectoryLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(btnGetClgDirectory)
                .addGap(35, 35, 35))
        );

        jPanelCollege_DirectoryLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel16});

        jPanelCollege_DirectoryLayout.setVerticalGroup(
            jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollege_DirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAddCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddcolleges)
                .addGap(41, 41, 41)
                .addGroup(jPanelCollege_DirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getClgDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetClgDirectory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDep_Dir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Directory", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        getDepartment.setText("Get Departments");
        getDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDepartmentActionPerformed(evt);
            }
        });

        clgDirDptMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clgDirDptMgmtActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("College list:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Departments:");

        addDeptList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeptListActionPerformed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Department:");

        btnAddDepartment.setText("Add Department");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDep_DirLayout = new javax.swing.GroupLayout(jPanelDep_Dir);
        jPanelDep_Dir.setLayout(jPanelDep_DirLayout);
        jPanelDep_DirLayout.setHorizontalGroup(
            jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDep_DirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDep_DirLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddDept))
                    .addGroup(jPanelDep_DirLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(clgDirDptMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDep_DirLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDep_DirLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(getDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDeptList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDep_DirLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel18, jLabel19, jLabel20});

        jPanelDep_DirLayout.setVerticalGroup(
            jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDep_DirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(clgDirDptMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDep_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(addDeptList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getDepartment)
                .addGap(60, 60, 60))
        );

        jPanelSem_Updt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Semester", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("College:");

        listClgSemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClgSemUpdateActionPerformed(evt);
            }
        });

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Departments:");

        listDpmtSemUdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDpmtSemUdtActionPerformed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Semesters:");

        listSemUpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSemUptActionPerformed(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Semester:");

        btnAddSem.setText("Add semester");
        btnAddSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSemActionPerformed(evt);
            }
        });

        btnSemUpdt.setText("Get Semester");
        btnSemUpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemUpdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSem_UpdtLayout = new javax.swing.GroupLayout(jPanelSem_Updt);
        jPanelSem_Updt.setLayout(jPanelSem_UpdtLayout);
        jPanelSem_UpdtLayout.setHorizontalGroup(
            jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSem_UpdtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddSem)
                .addGap(310, 310, 310))
            .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(18, 18, 18)
                                    .addComponent(listClgSemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(18, 18, 18)
                                    .addComponent(listDpmtSemUdt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSemUpdt)))
                            .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(listSemUpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnSemUpdt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSem_UpdtLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel23, jLabel24, jLabel25, jLabel26});

        jPanelSem_UpdtLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {listClgSemUpdate, listDpmtSemUdt, listSemUpt});

        jPanelSem_UpdtLayout.setVerticalGroup(
            jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSem_UpdtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(listClgSemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(listDpmtSemUdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtSemUpdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddSem)
                .addGap(14, 14, 14)
                .addGroup(jPanelSem_UpdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(listSemUpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSemUpdt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_University_ManagementLayout = new javax.swing.GroupLayout(jPanel_University_Management);
        jPanel_University_Management.setLayout(jPanel_University_ManagementLayout);
        jPanel_University_ManagementLayout.setHorizontalGroup(
            jPanel_University_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_University_ManagementLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_University_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelSem_Updt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_University_ManagementLayout.createSequentialGroup()
                        .addComponent(jPanelCollege_Directory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDep_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel_University_ManagementLayout.setVerticalGroup(
            jPanel_University_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_University_ManagementLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_University_ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDep_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCollege_Directory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelSem_Updt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_Admin.addTab("University Management", jPanel_University_Management);

        jPanelAdd_Std.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Student", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Student Name:");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Student Id:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        btnStudentAdd.setText("Add Student");
        btnStudentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdd_StdLayout = new javax.swing.GroupLayout(jPanelAdd_Std);
        jPanelAdd_Std.setLayout(jPanelAdd_StdLayout);
        jPanelAdd_StdLayout.setHorizontalGroup(
            jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd_StdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdd_StdLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdd_StdLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStudentAdd)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAdd_StdLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel27, jLabel28});

        jPanelAdd_StdLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtStudentId, txtStudentName});

        jPanelAdd_StdLayout.setVerticalGroup(
            jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd_StdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdd_StdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStudentAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelStd_Dir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Directory", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        studentDirList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student Id"
            }
        ));
        jScrollPane2.setViewportView(studentDirList);

        btnGetStudentDirectory.setText("View Student Directory");
        btnGetStudentDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStudentDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStd_DirLayout = new javax.swing.GroupLayout(jPanelStd_Dir);
        jPanelStd_Dir.setLayout(jPanelStd_DirLayout);
        jPanelStd_DirLayout.setHorizontalGroup(
            jPanelStd_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStd_DirLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnGetStudentDirectory)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanelStd_DirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelStd_DirLayout.setVerticalGroup(
            jPanelStd_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStd_DirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetStudentDirectory)
                .addGap(21, 21, 21))
        );

        jPanelFac_Dir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faculty Directory", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        btnGetDirectoryList.setText("View Faculty Directory");
        btnGetDirectoryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDirectoryListActionPerformed(evt);
            }
        });

        facultyDirectoryList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty Name", "Course"
            }
        ));
        jScrollPane4.setViewportView(facultyDirectoryList);

        javax.swing.GroupLayout jPanelFac_DirLayout = new javax.swing.GroupLayout(jPanelFac_Dir);
        jPanelFac_Dir.setLayout(jPanelFac_DirLayout);
        jPanelFac_DirLayout.setHorizontalGroup(
            jPanelFac_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFac_DirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFac_DirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetDirectoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanelFac_DirLayout.setVerticalGroup(
            jPanelFac_DirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFac_DirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGetDirectoryList))
        );

        jPanelAdd_Fac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Faculty", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel31.setText("Faculty Name:");

        txtAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddFacultyActionPerformed(evt);
            }
        });

        btnAddFaculty.setText("Add Faculty");
        btnAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdd_FacLayout = new javax.swing.GroupLayout(jPanelAdd_Fac);
        jPanelAdd_Fac.setLayout(jPanelAdd_FacLayout);
        jPanelAdd_FacLayout.setHorizontalGroup(
            jPanelAdd_FacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd_FacLayout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdd_FacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFaculty)
                    .addComponent(txtAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanelAdd_FacLayout.setVerticalGroup(
            jPanelAdd_FacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd_FacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdd_FacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddFaculty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_DirectoriesLayout = new javax.swing.GroupLayout(jPanel_Directories);
        jPanel_Directories.setLayout(jPanel_DirectoriesLayout);
        jPanel_DirectoriesLayout.setHorizontalGroup(
            jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelStd_Dir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFac_Dir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdd_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAdd_Std, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_DirectoriesLayout.setVerticalGroup(
            jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                .addGroup(jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelStd_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanelAdd_Std, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelFac_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DirectoriesLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanelAdd_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane_Admin.addTab("Directories", jPanel_Directories);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCMcourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMcourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMcourseNameActionPerformed

    private void btnAddToCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCatalogActionPerformed
        
        String collegeName = (String) listCourseMgmtClg.getSelectedItem();
        String deptName = (String) listCorseMgmtDpmtList.getSelectedItem();
        university.addNewCourse(collegeName, deptName, txtCMcourseName.getText(), txtCMCourseNo.getText(), Integer.parseInt(txtCMcr.getText()));

    }//GEN-LAST:event_btnAddToCatalogActionPerformed

    private void btnViewCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCatalogActionPerformed
        // TODO add your handling code here:
        
        String collegeName = (String) listCourseMgmtClg.getSelectedItem();
        String deptName = (String) listCorseMgmtDpmtList.getSelectedItem();
        
        ArrayList<Department> deptList = university.getDepartmenList(collegeName);
         
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        ArrayList<Course> courseList = university.viewCourseCatalog(collegeName, deptName);
        
        
        for(Course c : courseList)
        {
            dl.addElement(c.getCourseName());
        }
        listCmCatalog.setModel(dl);
          
    }//GEN-LAST:event_btnViewCatalogActionPerformed

    private void txtAddCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCollegeActionPerformed

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        
        String college = (String) clgDirDptMgmt.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         String department = txtAddDept.getText();
        university.addDepartment(college, department);
        
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void addDeptListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeptListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDeptListActionPerformed

    private void btnGetClgDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetClgDirectoryActionPerformed
        // TODO add your handling code here:
         ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        getClgDir.setModel(dl);
         
    }//GEN-LAST:event_btnGetClgDirectoryActionPerformed

    private void btnAddcollegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddcollegesActionPerformed
        // TODO add your handling code here:
        university.addNewCollege(txtAddCollege.getText());
    }//GEN-LAST:event_btnAddcollegesActionPerformed

    private void getDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDepartmentActionPerformed
        // TODO add your handling code here:
        ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        clgDirDptMgmt.setModel(dl);
         
    }//GEN-LAST:event_getDepartmentActionPerformed

    private void clgDirDptMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clgDirDptMgmtActionPerformed
        // TODO add your handling code here:
        String college = (String) clgDirDptMgmt.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(Department d: deptList)
        {
            dl.addElement(d.getDepartmentName());
        }
        addDeptList.setModel(dl);
    }//GEN-LAST:event_clgDirDptMgmtActionPerformed

    private void scheduleMgmtClgListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleMgmtClgListActionPerformed
        // TODO add your handling code here:
        String college = (String) scheduleMgmtClgList.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         DefaultComboBoxModel dx = new DefaultComboBoxModel();
        for(Department d: deptList)
        {
            dx.addElement(d.getDepartmentName());
        }
        scheduleMgtDpmtList.setModel(dx);                 
        
    }//GEN-LAST:event_scheduleMgmtClgListActionPerformed

    private void scheduleMgtDpmtListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleMgtDpmtListActionPerformed
        // TODO add your handling code here:
        String college = (String) scheduleMgmtClgList.getSelectedItem();
        String department = (String) scheduleMgtDpmtList.getSelectedItem();
        
        ArrayList<String> semList = university.viewSemesters(college, department);
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(String s: semList)
        {
            dl.addElement(s);
        }
        scheduleSemList.setModel(dl);
        
        
        
    }//GEN-LAST:event_scheduleMgtDpmtListActionPerformed

    private void schdlMgmtGetScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schdlMgmtGetScheduleActionPerformed
        // TODO add your handling code here:
        
        
         ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        scheduleMgmtClgList.setModel(dl);
            
    }//GEN-LAST:event_schdlMgmtGetScheduleActionPerformed

    private void listCourseMgmtClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCourseMgmtClgActionPerformed

        String college = (String) listCourseMgmtClg.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         DefaultComboBoxModel dx = new DefaultComboBoxModel();
        for(Department d: deptList)
        {
            dx.addElement(d.getDepartmentName());
        }
        listCorseMgmtDpmtList.setModel(dx);    
    }//GEN-LAST:event_listCourseMgmtClgActionPerformed

    private void btnSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCoursesActionPerformed
        // TODO add your handling code here:
         ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        listCourseMgmtClg.setModel(dl);
    }//GEN-LAST:event_btnSearchCoursesActionPerformed

    private void btnSemUpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemUpdtActionPerformed
        // TODO add your handling code here:
        ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        listClgSemUpdate.setModel(dl);
    }//GEN-LAST:event_btnSemUpdtActionPerformed

    private void listClgSemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClgSemUpdateActionPerformed
        // TODO add your handling code here:
         String college = (String) listClgSemUpdate.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(Department d: deptList)
        {
            dl.addElement(d.getDepartmentName());
        }
        listDpmtSemUdt.setModel(dl);
    }//GEN-LAST:event_listClgSemUpdateActionPerformed

    private void listDpmtSemUdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDpmtSemUdtActionPerformed
        // TODO add your handling code here:
        String college = (String) listClgSemUpdate.getSelectedItem();
        String department = (String) listDpmtSemUdt.getSelectedItem();
        ArrayList<String> semList = university.viewSemesters(college, department);
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(String s: semList)
        {
            dl.addElement(s);
        }
        listSemUpt.setModel(dl);
    }//GEN-LAST:event_listDpmtSemUdtActionPerformed

    private void btnAddSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSemActionPerformed
        // TODO add your handling code here:
        String college = (String) listClgSemUpdate.getSelectedItem();
        String department = (String) listDpmtSemUdt.getSelectedItem();
        university.addSemester(college,department,txtSemUpdt.getText());
        
    }//GEN-LAST:event_btnAddSemActionPerformed

    private void courseListSchdMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseListSchdMgmtActionPerformed
        // TODO add your handling code here:
        ArrayList<FacultyProfile> facultyProfile  = FacultyDirectory.getTeacherlist();
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(FacultyProfile f: facultyProfile)
        {
            dl.addElement(f.getFacultyName());
        }
        facultyList.setModel(dl);
        
        
    }//GEN-LAST:event_courseListSchdMgmtActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFacultyActionPerformed
        facultyprofile = new FacultyProfile(txtAddFaculty.getText());
        facultydirectory.addFaculty(facultyprofile);
        
    }//GEN-LAST:event_btnAddFacultyActionPerformed

    private void scheduleSemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleSemListActionPerformed
        String college = (String) scheduleMgmtClgList.getSelectedItem();
        String department = (String) scheduleMgtDpmtList.getSelectedItem();
        String semester = (String) scheduleSemList.getSelectedItem();
        ArrayList<Course> courseList = university.viewCourseCatalog(college,department);
        
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(Course c : courseList)
        {
            dl.addElement(c.getCourseName());
        }
        courseListSchdMgmt.setModel(dl);
        
        ArrayList<CourseOffer> coursesOffered = university.getCoursesOffered(college,department,semester);
        DefaultTableModel dx = (DefaultTableModel) tblSchedule.getModel();
        //String[] row = {null,null,null};
        dx.setRowCount(0);
        
        for(CourseOffer co: coursesOffered)
        {
            String[] row = {co.getCourseName(),co.getFacultyProfile().getFacultyName(),co.getNoOfSeats()};
            dx.addRow(row);
        }
        
        tblSchedule.setModel(dx);
        
        
    }//GEN-LAST:event_scheduleSemListActionPerformed

    private void btnAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddScheduleActionPerformed
        String college = (String) scheduleMgmtClgList.getSelectedItem();
        String department = (String) scheduleMgtDpmtList.getSelectedItem();
        String semester = (String) scheduleSemList.getSelectedItem();
        String course = (String) courseListSchdMgmt.getSelectedItem();
        String faculty = (String) facultyList.getSelectedItem();
        int n =  Integer.parseInt(txtNoOfSeats.getText());
        
        university.scheduleCourse(college,department,semester,course,faculty,n);
    }//GEN-LAST:event_btnAddScheduleActionPerformed

    private void btnGetDirectoryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDirectoryListActionPerformed
        // TODO add your handling code here:
        ArrayList<FacultyProfile> facutlyDirectory = FacultyDirectory.getTeacherlist();
        DefaultTableModel dx = (DefaultTableModel) facultyDirectoryList.getModel();
        dx.setRowCount(0);
        
        for(FacultyProfile fp: facutlyDirectory)
        {
            String[] row = {fp.getFacultyName()};
            dx.addRow(row);
        }
        
        facultyDirectoryList.setModel(dx);
        
    }//GEN-LAST:event_btnGetDirectoryListActionPerformed

    private void btnStudentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAddActionPerformed
        // TODO add your handling code here:
        studentProfile = new StudentProfile(txtStudentName.getText(),txtStudentId.getText());
        StudentDirectory.addStudentToDirectory(studentProfile);
    }//GEN-LAST:event_btnStudentAddActionPerformed

    private void btnGetStudentDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStudentDirectoryActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentProfile> studentDirectory = StudentDirectory.getStudentlist();
        DefaultTableModel dx = (DefaultTableModel) studentDirList.getModel();
        dx.setRowCount(0);
        for(StudentProfile sp : studentDirectory)
        {
            String[] row = {sp.getStudentName(),sp.getStudentId()};
            dx.addRow(row);
        }
        studentDirList.setModel(dx);
    }//GEN-LAST:event_btnGetStudentDirectoryActionPerformed

    private void listCorseMgmtDpmtListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCorseMgmtDpmtListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCorseMgmtDpmtListActionPerformed

    private void listSemUptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSemUptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSemUptActionPerformed

    private void txtAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddFacultyActionPerformed

    private void btnGenerateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportsActionPerformed
        // TODO add your handling code here:

        ArrayList<College> collegeList = university.getCollegeList();
        DefaultTableModel dm = (DefaultTableModel) courseData.getModel();
        dm.setRowCount(0);
        for(College c: collegeList)
        {
            ArrayList<Department> departmentList = c.getDepartmentList();

            for(Department d: departmentList)
            {
                HashMap<String, CourseSchedule> masterCourseSchedule = d.getMastercoursecatalog();

                for(String key : masterCourseSchedule.keySet())
                {
                    CourseSchedule cs = masterCourseSchedule.get(key);
                    ArrayList<CourseOffer> coursesOffered = cs.getSchedule();

                    for(CourseOffer co : coursesOffered)
                    {
                        String[] row = {co.getCourseName(),co.getFacultyProfile().getFacultyName(),co.getNoOfSeats()};
                        dm.addRow(row);
                    }

                }
            }
        }

        courseData.setModel(dm);

        DefaultTableModel dx = (DefaultTableModel) financialData.getModel();
        dx.setRowCount(0);
        for(College c: collegeList)
        {
            ArrayList<Department> departmentList = c.getDepartmentList();

            for(Department d: departmentList)
            {
                HashMap<String, CourseSchedule> masterCourseSchedule = d.getMastercoursecatalog();

                for(String key : masterCourseSchedule.keySet())
                {
                    CourseSchedule cs = masterCourseSchedule.get(key);
                    ArrayList<CourseOffer> coursesOffered = cs.getSchedule();

                    for(CourseOffer co : coursesOffered)
                    {
                        String[] row = {c.getCollegeName(),d.getDepartmentName(),co.getTotalRevenueOfCourse()};
                        dx.addRow(row);
                    }

                }
            }
        }

        financialData.setModel(dx);

    }//GEN-LAST:event_btnGenerateReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addDeptList;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddFaculty;
    private javax.swing.JButton btnAddSchedule;
    private javax.swing.JButton btnAddSem;
    private javax.swing.JButton btnAddToCatalog;
    private javax.swing.JButton btnAddcolleges;
    private javax.swing.JButton btnGenerateReports;
    private javax.swing.JButton btnGetClgDirectory;
    private javax.swing.JButton btnGetDirectoryList;
    private javax.swing.JButton btnGetStudentDirectory;
    private javax.swing.JButton btnSearchCourses;
    private javax.swing.JButton btnSemUpdt;
    private javax.swing.JButton btnStudentAdd;
    private javax.swing.JButton btnViewCatalog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> clgDirDptMgmt;
    private javax.swing.JTable courseData;
    private javax.swing.JComboBox<String> courseListSchdMgmt;
    private javax.swing.JTable facultyDirectoryList;
    private javax.swing.JComboBox<String> facultyList;
    private javax.swing.JTable financialData;
    private javax.swing.JComboBox<String> getClgDir;
    private javax.swing.JButton getDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAdd_Fac;
    private javax.swing.JPanel jPanelAdd_Std;
    private javax.swing.JPanel jPanelCollege_Directory;
    private javax.swing.JPanel jPanelCourse;
    private javax.swing.JPanel jPanelDep_Dir;
    private javax.swing.JPanel jPanelFac_Dir;
    private javax.swing.JPanel jPanelSem_Updt;
    private javax.swing.JPanel jPanelStd_Dir;
    private javax.swing.JPanel jPanel_Analytics;
    private javax.swing.JPanel jPanel_Course_Management;
    private javax.swing.JPanel jPanel_Directories;
    private javax.swing.JPanel jPanel_Schedule_Management;
    private javax.swing.JPanel jPanel_University_Management;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane_Admin;
    private javax.swing.JComboBox<String> listClgSemUpdate;
    private javax.swing.JList<String> listCmCatalog;
    private javax.swing.JComboBox<String> listCorseMgmtDpmtList;
    private javax.swing.JComboBox<String> listCourseMgmtClg;
    private javax.swing.JComboBox<String> listDpmtSemUdt;
    private javax.swing.JComboBox<String> listSemUpt;
    private javax.swing.JButton schdlMgmtGetSchedule;
    private javax.swing.JComboBox<String> scheduleMgmtClgList;
    private javax.swing.JComboBox<String> scheduleMgtDpmtList;
    private javax.swing.JComboBox<String> scheduleSemList;
    private javax.swing.JTable studentDirList;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtAddCollege;
    private javax.swing.JTextField txtAddDept;
    private javax.swing.JTextField txtAddFaculty;
    private javax.swing.JTextField txtCMCourseNo;
    private javax.swing.JTextField txtCMcourseName;
    private javax.swing.JTextField txtCMcr;
    private javax.swing.JTextField txtNoOfSeats;
    private javax.swing.JTextField txtSemUpdt;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
