/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.administrator;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Department.Department;
import info5100.university.example.Employer.JobDetails;
import info5100.university.example.Employer.JobDetailsList;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.college.College;
import info5100.university.example.university.University;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author isham.
 */
public class StudentPortal extends javax.swing.JPanel {

    /**
     * Creates new form StudentPortal
     */
    String sid;
    University university;
    StudentDirectory studentDirectory;
    public StudentPortal(University university,StudentDirectory sd) {
        initComponents();
        this.university = university;
        this.studentDirectory = sd;
        jPanel_StudentProfile.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Student = new javax.swing.JTabbedPane();
        jPanel_Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtField_StudentID = new javax.swing.JTextField();
        jPanel_StudentProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtField_Course_Load = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtField_Gpa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtField_Job_Offers = new javax.swing.JTextField();
        jTxtField_Name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_Verify = new javax.swing.JButton();
        jPanel_Course = new javax.swing.JPanel();
        combo_College = new javax.swing.JComboBox<>();
        combo_Department = new javax.swing.JComboBox<>();
        combo_Semester = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Enroll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Courses_Available = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_Get_College = new javax.swing.JButton();
        btn_Get_Data = new javax.swing.JButton();
        jPanel_Finance = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        enrolledTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCrEnr = new javax.swing.JTextField();
        txtCstPerCr = new javax.swing.JTextField();
        txtTotalSemCost = new javax.swing.JTextField();
        btnCoursesSidEnrolled = new javax.swing.JButton();
        btnCalculateCost = new javax.swing.JButton();
        jPanel_Job = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jobListTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welcome!");

        jLabel16.setText("Please enter your Student ID.");

        jLabel17.setText("StudentID:");

        jPanel_StudentProfile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Profile", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Current Course Load:");

        jTxtField_Course_Load.setEditable(false);
        jTxtField_Course_Load.setBackground(new java.awt.Color(204, 204, 204));
        jTxtField_Course_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_Course_LoadActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("GPA:");

        jTxtField_Gpa.setEditable(false);
        jTxtField_Gpa.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Job Offers:");

        jTxtField_Job_Offers.setEditable(false);
        jTxtField_Job_Offers.setBackground(new java.awt.Color(204, 204, 204));
        jTxtField_Job_Offers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_Job_OffersActionPerformed(evt);
            }
        });

        jTxtField_Name.setEditable(false);
        jTxtField_Name.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Name:");

        javax.swing.GroupLayout jPanel_StudentProfileLayout = new javax.swing.GroupLayout(jPanel_StudentProfile);
        jPanel_StudentProfile.setLayout(jPanel_StudentProfileLayout);
        jPanel_StudentProfileLayout.setHorizontalGroup(
            jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StudentProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_StudentProfileLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_StudentProfileLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtField_Job_Offers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_StudentProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtField_Course_Load, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtField_Gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_StudentProfileLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel18, jLabel2, jLabel3, jLabel4});

        jPanel_StudentProfileLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTxtField_Course_Load, jTxtField_Gpa, jTxtField_Job_Offers, jTxtField_Name});

        jPanel_StudentProfileLayout.setVerticalGroup(
            jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StudentProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTxtField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtField_Course_Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtField_Gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_StudentProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtField_Job_Offers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_Verify.setText("Verify");
        btn_Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_HomeLayout = new javax.swing.GroupLayout(jPanel_Home);
        jPanel_Home.setLayout(jPanel_HomeLayout);
        jPanel_HomeLayout.setHorizontalGroup(
            jPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(jPanel_StudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_Verify)
                        .addGroup(jPanel_HomeLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtField_StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel_HomeLayout.setVerticalGroup(
            jPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HomeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTxtField_StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Verify)
                .addGap(19, 19, 19)
                .addComponent(jPanel_StudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane_Student.addTab("Home", jPanel_Home);

        combo_College.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_CollegeActionPerformed(evt);
            }
        });

        combo_Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_DepartmentActionPerformed(evt);
            }
        });

        combo_Semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_SemesterActionPerformed(evt);
            }
        });

        jLabel5.setText("Semester:");

        jLabel6.setText("Department:");

        jLabel7.setText("College:");

        btn_Enroll.setText("Enroll");
        btn_Enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnrollActionPerformed(evt);
            }
        });

        jTable_Courses_Available.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Professor", "No Of Seats"
            }
        ));
        jScrollPane2.setViewportView(jTable_Courses_Available);

        jLabel8.setText("Courses Available:");

        btn_Get_College.setText("Get College");
        btn_Get_College.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Get_CollegeActionPerformed(evt);
            }
        });

        btn_Get_Data.setText("Get data");
        btn_Get_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Get_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CourseLayout = new javax.swing.GroupLayout(jPanel_Course);
        jPanel_Course.setLayout(jPanel_CourseLayout);
        jPanel_CourseLayout.setHorizontalGroup(
            jPanel_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_CourseLayout.createSequentialGroup()
                .addGroup(jPanel_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_CourseLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Enroll))
                    .addGroup(jPanel_CourseLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_College, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_Semester, 0, 166, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_CourseLayout.createSequentialGroup()
                .addComponent(btn_Get_College)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Get_Data))
        );
        jPanel_CourseLayout.setVerticalGroup(
            jPanel_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CourseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_College, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Get_College)
                    .addComponent(btn_Get_Data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Enroll)
                .addGap(186, 186, 186))
        );

        jTabbedPane_Student.addTab("Course Management", jPanel_Course);

        jLabel10.setText("Courses Enrolled:");

        enrolledTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Course Number", "Credits"
            }
        ));
        jScrollPane3.setViewportView(enrolledTable);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Total Credits Enrolled:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cost Per Credit:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Total Semester Cost:");

        txtCrEnr.setEditable(false);
        txtCrEnr.setBackground(new java.awt.Color(204, 204, 204));

        txtCstPerCr.setEditable(false);
        txtCstPerCr.setBackground(new java.awt.Color(204, 204, 204));

        txtTotalSemCost.setEditable(false);
        txtTotalSemCost.setBackground(new java.awt.Color(204, 204, 204));

        btnCoursesSidEnrolled.setText("Get Enrolled Courses");
        btnCoursesSidEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesSidEnrolledActionPerformed(evt);
            }
        });

        btnCalculateCost.setText("Calculate Cost");
        btnCalculateCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_FinanceLayout = new javax.swing.GroupLayout(jPanel_Finance);
        jPanel_Finance.setLayout(jPanel_FinanceLayout);
        jPanel_FinanceLayout.setHorizontalGroup(
            jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                        .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtCstPerCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalSemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtCrEnr, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FinanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalculateCost)
                    .addComponent(btnCoursesSidEnrolled))
                .addGap(14, 14, 14))
        );

        jPanel_FinanceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13});

        jPanel_FinanceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCrEnr, txtCstPerCr, txtTotalSemCost});

        jPanel_FinanceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCalculateCost, btnCoursesSidEnrolled});

        jPanel_FinanceLayout.setVerticalGroup(
            jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinanceLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCoursesSidEnrolled)
                .addGap(10, 10, 10)
                .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCrEnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCstPerCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_FinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTotalSemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCalculateCost)
                .addGap(40, 40, 40))
        );

        jTabbedPane_Student.addTab("Student Finance", jPanel_Finance);

        jLabel14.setText("Jobs Available:");

        jobListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Job Title", "Job Type", "Pay"
            }
        ));
        jScrollPane4.setViewportView(jobListTable);

        jButton5.setText("Get Jobs");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_JobLayout = new javax.swing.GroupLayout(jPanel_Job);
        jPanel_Job.setLayout(jPanel_JobLayout);
        jPanel_JobLayout.setHorizontalGroup(
            jPanel_JobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_JobLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_JobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(jPanel_JobLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_JobLayout.setVerticalGroup(
            jPanel_JobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_JobLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_JobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane_Student.addTab("Job Portal", jPanel_Job);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Student, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane_Student)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_DepartmentActionPerformed
        // TODO add your handling code here:
          String college = (String) combo_College.getSelectedItem();
        String department = (String) combo_Department.getSelectedItem();
        
        ArrayList<String> semList = university.viewSemesters(college, department);
        DefaultComboBoxModel dl = new DefaultComboBoxModel();
        for(String s: semList)
        {
            dl.addElement(s);
        }
        combo_Semester.setModel(dl);
        
        
    }//GEN-LAST:event_combo_DepartmentActionPerformed

    private void jTxtField_Course_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_Course_LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_Course_LoadActionPerformed

    private void jTxtField_Job_OffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_Job_OffersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_Job_OffersActionPerformed

    private void btn_VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerifyActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentProfile> studentDirectory = StudentDirectory.getStudentlist();
        String id = jTxtField_StudentID.getText();
        
        String name = null;
        for(StudentProfile sp: studentDirectory){
            
            if(sp.getStudentId().equals(id)){
                name = sp.getStudentName();
                this.sid = id;
            }
            
            
        }
        if(name==null){
            
            JOptionPane.showMessageDialog(this,"Student ID doesn't exist. Please re-enter Student ID.");
            
        }
        else{
            
            jPanel_StudentProfile.setVisible(true);
                jTxtField_Name.setText(name);
        }
            
        
       
        /*if(studentDirectory.studentExists(id) == true)
        {
            
            jPanel_StudentProfile.setVisible(true);
            for(StudentProfile sp : studentDirectory)
        {
         jTxtField_Name.setText(sp.getStudentName());
        }
        }else{
            JOptionPane.showMessageDialog(this,"Student ID doesn't exist. Please re-enter Student ID.");
        }*/
    }//GEN-LAST:event_btn_VerifyActionPerformed

    private void combo_CollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_CollegeActionPerformed
        // TODO add your handling code here:
        String college = (String) combo_College.getSelectedItem();
        ArrayList<Department> deptList = university.getDepartmenList(college);
         DefaultComboBoxModel dx = new DefaultComboBoxModel();
        for(Department d: deptList)
        {
            dx.addElement(d.getDepartmentName());
        }
        combo_Department.setModel(dx);                 
    }//GEN-LAST:event_combo_CollegeActionPerformed

    private void combo_SemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_SemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_SemesterActionPerformed

    private void btn_Get_CollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Get_CollegeActionPerformed
        // TODO add your handling code here:
        
         ArrayList<College> collegeList = university.getCollegeList();
         
         DefaultComboBoxModel dl = new DefaultComboBoxModel();
        
        for(College c : collegeList)
        {
            dl.addElement(c.getCollegeName());
        }
        combo_College.setModel(dl);
    }//GEN-LAST:event_btn_Get_CollegeActionPerformed

    private void btn_Get_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Get_DataActionPerformed
        // TODO add your handling code here:
        String college = (String) combo_College.getSelectedItem();
        String department = (String) combo_Department.getSelectedItem();
        String semester = (String) combo_Semester.getSelectedItem();
        ArrayList<Course> courseList = university.viewCourseCatalog(college,department);
        
        
        ArrayList<CourseOffer> coursesOffered = university.getCoursesOffered(college,department,semester);
        DefaultTableModel dx = (DefaultTableModel) jTable_Courses_Available.getModel();
        //String[] row = {null,null,null};
        
        
        for(CourseOffer co: coursesOffered)
        {
            String[] row = {co.getCourseName(),co.getFacultyProfile().getFacultyName(),co.getNoOfSeats()};
            dx.addRow(row);
        }
        
        jTable_Courses_Available.setModel(dx);
        
        
    }//GEN-LAST:event_btn_Get_DataActionPerformed

    private void btn_EnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnrollActionPerformed
        String college = (String) combo_College.getSelectedItem();
        String department = (String) combo_Department.getSelectedItem();
        String semester = (String) combo_Semester.getSelectedItem();
        ArrayList<Course> courseList = university.viewCourseCatalog(college,department);
        
        DefaultTableModel df = (DefaultTableModel) jTable_Courses_Available.getModel();
          int selectedRow = jTable_Courses_Available.getSelectedRow();
          
          
          HashMap<String,ArrayList<Course>> coursesStudentEnrolled = university.getCoursesStudentsEnrrolled();
          
          boolean flag = false;
          
          if(coursesStudentEnrolled.isEmpty())
              
              coursesStudentEnrolled.put(sid,new ArrayList<Course>());
          else {
              for(String key : coursesStudentEnrolled.keySet())
              {
                  if(key.equals(sid))
                      flag = true;
              }
        }  
         
          if(flag == false)
              coursesStudentEnrolled.put(sid,new ArrayList<Course>());
          
          String courseName = df.getValueAt(selectedRow,0).toString();
          ArrayList<Course> coursesSidEnrolled = coursesStudentEnrolled.get(sid);
        
          for(Course c: courseList)
        {
             if(c.getCourseName().equals(courseName))
             {
                 coursesSidEnrolled.add(c);
                 
             }
        }
        
        
                
    }//GEN-LAST:event_btn_EnrollActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<JobDetails> jobDetailList = JobDetailsList.getJa();
        
        DefaultTableModel df = (DefaultTableModel) jobListTable.getModel();
        df.setRowCount(0);
        for(JobDetails jd : jobDetailList)
        {
            String[] row = {jd.getJobTitle(),jd.getJobType(),String.valueOf(jd.getPayScale())};
            df.addRow(row);
        }
        
        jobListTable.setModel(df);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCoursesSidEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesSidEnrolledActionPerformed
        // TODO add your handling code here:
        HashMap<String,ArrayList<Course>> coursesStudentEnrolled = university.getCoursesStudentsEnrrolled();
        ArrayList<Course> coursesSidEnrolled = coursesStudentEnrolled.get(sid);
        
        DefaultTableModel df = (DefaultTableModel) enrolledTable.getModel();
        df.setRowCount(0);
        for(Course c: coursesSidEnrolled)
        {
            String[] row = {c.getCourseName(),c.getCOurseNumber(),c.getCredits()};
            df.addRow(row);
        }
        
        enrolledTable.setModel(df);
        
    }//GEN-LAST:event_btnCoursesSidEnrolledActionPerformed

    private void btnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCostActionPerformed
        // TODO add your handling code here:
       HashMap<String,ArrayList<Course>> coursesStudentEnrolled = university.getCoursesStudentsEnrrolled();
        ArrayList<Course> coursesSidEnrolled = coursesStudentEnrolled.get(sid);
        
        int credits = 0,costPerCredit = 0,SemCost = 0;
        for(Course c: coursesSidEnrolled)
        {
            credits = Integer.parseInt(c.getCredits()) + credits;
            txtCstPerCr.setText(String.valueOf(c.getCredits()));
            costPerCredit = Integer.parseInt(c.getCredits());
        }
        
        txtCrEnr.setText(String.valueOf(credits));
        txtTotalSemCost.setText(String.valueOf(credits*costPerCredit));
        
         
    }//GEN-LAST:event_btnCalculateCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateCost;
    private javax.swing.JButton btnCoursesSidEnrolled;
    private javax.swing.JButton btn_Enroll;
    private javax.swing.JButton btn_Get_College;
    private javax.swing.JButton btn_Get_Data;
    private javax.swing.JButton btn_Verify;
    private javax.swing.JComboBox<String> combo_College;
    private javax.swing.JComboBox<String> combo_Department;
    private javax.swing.JComboBox<String> combo_Semester;
    private javax.swing.JTable enrolledTable;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_Course;
    private javax.swing.JPanel jPanel_Finance;
    private javax.swing.JPanel jPanel_Home;
    private javax.swing.JPanel jPanel_Job;
    private javax.swing.JPanel jPanel_StudentProfile;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane_Student;
    private javax.swing.JTable jTable_Courses_Available;
    private javax.swing.JTextField jTxtField_Course_Load;
    private javax.swing.JTextField jTxtField_Gpa;
    private javax.swing.JTextField jTxtField_Job_Offers;
    private javax.swing.JTextField jTxtField_Name;
    private javax.swing.JTextField jTxtField_StudentID;
    private javax.swing.JTable jobListTable;
    private javax.swing.JTextField txtCrEnr;
    private javax.swing.JTextField txtCstPerCr;
    private javax.swing.JTextField txtTotalSemCost;
    // End of variables declaration//GEN-END:variables
        
}